apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
  labels:
    app: healthcare
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-service
spec:
  type: NodePort
  selector:
    app: healthcare
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30090
